apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    stage: staging
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: stage
        operator: In
        values:
          - prod
          - staging
  template:
    metadata:
      labels:
        stage: staging  # prod 또는 staging에 따라 변경 가능
    spec:
      containers:
        - image: nginx
          name: nginx
