apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    stage: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      stage: stage
  template:
    metadata:
      labels:
        stage: stage
    spec:
      containers:
      - image: nginx
        name: nginx
